/**
 * @tenmol/protocol — the topic barrel.  ** FROZEN — WRITTEN ONCE BY WP-01 **
 *
 * ============================================================================
 *  DO NOT EDIT THIS FILE.
 *
 *  Plan §5.2 / §A8: the twelve file collisions are resolved structurally, by
 *  replacing every shared file with a directory of one-file-per-owner modules
 *  plus "a barrel written once in wave 0 and never touched again". This is that
 *  barrel. Every later work package fills in ITS OWN `topics/<name>.ts` and
 *  touches nothing here. Two agents editing this file corrupts the run.
 *
 *  The contract each owner must honour is exactly one line long: keep exporting
 *  a type named `<Name>Payload` from your module. Everything inside it is
 *  yours; the name is the barrel's.
 * ============================================================================
 *
 * 19 modules: the 18 v1 topics of plan §6, plus `geometry` — promoted onto the
 * critical path by the product owner (Mode G is developed in parallel with
 * Mode P from the start, not deferred to post-v1 WP-26).
 */

/* --- the registry (no imports, no cycles) --------------------------------- */

export {
  TOPICS,
  TOPIC_META,
  BINARY_SIDECAR_TOPICS,
  DESTRUCTIVE_DRAIN_TOPICS,
  isTopic,
  type Topic,
  type TopicMeta,
  type TopicSource,
} from './_registry';

import type { Topic } from './_registry';

/* --- the 19 topic modules ------------------------------------------------- */

export * from './feedback'; // WP-03
export * from './progress'; // WP-03
export * from './redisplay'; // WP-03
export * from './pixels'; // WP-04
export * from './view'; // WP-09
export * from './selection'; // WP-10
export * from './objects'; // WP-12
export * from './menu'; // WP-13
export * from './settings'; // WP-15
export * from './wizard'; // WP-16
export * from './editor'; // WP-17
export * from './dialog'; // WP-18
export * from './frame'; // WP-20
export * from './scenes'; // WP-20
export * from './movie_panel'; // WP-20
export * from './seqview'; // WP-21
export * from './colors'; // WP-22
export * from './plugin'; // WP-25
export * from './geometry'; // WP-26

import type { FeedbackPayload } from './feedback';
import type { ProgressPayload } from './progress';
import type { RedisplayPayload } from './redisplay';
import type { PixelsPayload } from './pixels';
import type { ViewPayload } from './view';
import type { SelectionPayload } from './selection';
import type { ObjectsPayload } from './objects';
import type { MenuPayload } from './menu';
import type { SettingsPayload } from './settings';
import type { WizardPayload } from './wizard';
import type { EditorPayload } from './editor';
import type { DialogPayload } from './dialog';
import type { FramePayload } from './frame';
import type { ScenesPayload } from './scenes';
import type { MoviePanelPayload } from './movie_panel';
import type { SeqviewPayload } from './seqview';
import type { ColorsPayload } from './colors';
import type { PluginPayload } from './plugin';
import type { GeometryPayload } from './geometry';

/* --- topic -> payload ----------------------------------------------------- */

export interface TopicPayloads {
  feedback: FeedbackPayload;
  progress: ProgressPayload;
  redisplay: RedisplayPayload;
  pixels: PixelsPayload;
  view: ViewPayload;
  selection: SelectionPayload;
  objects: ObjectsPayload;
  menu: MenuPayload;
  settings: SettingsPayload;
  wizard: WizardPayload;
  editor: EditorPayload;
  dialog: DialogPayload;
  frame: FramePayload;
  scenes: ScenesPayload;
  movie_panel: MoviePanelPayload;
  seqview: SeqviewPayload;
  colors: ColorsPayload;
  plugin: PluginPayload;
  geometry: GeometryPayload;
}

/** Payload type for a given topic. */
export type PayloadFor<T extends Topic> = TopicPayloads[T];

/**
 * Compile-time proof that `TopicPayloads` covers exactly `TOPICS` — no missing
 * entry, no stray one. If a later WP renames its payload type, or the registry
 * and the map drift apart, THIS is where the build breaks. That is the point.
 */
type Assert<T extends true> = T;
type _TopicsAreCovered = Assert<Topic extends keyof TopicPayloads ? true : false>;
type _NoExtraPayloadKeys = Assert<keyof TopicPayloads extends Topic ? true : false>;

/** Exported so the checks above are not flagged as unused. */
export type TopicCoverageProof = [_TopicsAreCovered, _NoExtraPayloadKeys];
