/**
 * Turn `api-schema.json` into a Mintlify MDX API reference.
 *
 *     node tools/gen-api/emit-docs.mjs <schema.json> <out-dir>
 *     node tools/gen-api/emit-docs.mjs                     # uses repo defaults
 *
 * This is the docs sibling of `emit.mjs`. Both read the SAME committed schema
 * (`tools/gen-api/api-schema.json`, produced from a live PyMOL by extract.py),
 * so this runs with node alone — no PyMOL, no venv — which is why the CI
 * staleness gate can live in the fast `static` job.
 *
 * Output is deterministic (keys are sorted, nothing is timestamped) so a
 * `git diff --exit-code docs/api-reference` after regeneration is the gate:
 * committed MDX that drifts from the schema fails CI, exactly like the
 * committed TypeScript in packages/protocol/src/generated/.
 *
 * The pages land under docs/api-reference/ — inside the Mintlify content root
 * (docs/), which is neither git-ignored nor linted nor prettier-formatted, so
 * generated MDX never fights a formatter.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');

/**
 * Commands that execute arbitrary text or end the session. Mirrors the set in
 * emit.mjs so the two generators agree on what "unsafe" means.
 */
const UNSAFE = new Set(['do', 'run', 'runpy', 'extend', 'new_command', 'alias', 'quit', 'system']);

const GENERATED_NOTE =
  '{/* GENERATED by tools/gen-api/emit-docs.mjs — do not edit. Regenerate with `pnpm docs:api`. */}';

/**
 * Escape the characters MDX would otherwise read as JSX (`<`, `>`) or an
 * expression (`{`, `}`). Applied to every piece of free text pulled from the
 * schema so a PyMOL docstring containing `<selection>` cannot break the build.
 * Code spans and fenced blocks are emitted separately and left untouched.
 */
function esc(text) {
  return String(text)
    .replace(/\\/g, '\\\\')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\{/g, '&#123;')
    .replace(/\}/g, '&#125;')
    .replace(/\|/g, '\\|');
}

/** First `max` non-empty lines of a docstring section, escaped and joined. */
function summarize(section, max = 8) {
  const text = (section ?? '').trim();
  if (!text) return '';
  return text
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .slice(0, max)
    .map(esc)
    .join(' ');
}

/** Human default: schema stores it as a source string, or null for "no default". */
function defaultCell(param) {
  if (param.default === null || param.default === undefined) return '';
  return '`' + param.default + '`';
}

/** A markdown parameters table for one command, or '' when it takes none. */
function paramsTable(spec) {
  const rows = spec.params.filter(
    (p) => p.kind !== 'VAR_POSITIONAL' && p.kind !== 'VAR_KEYWORD',
  );
  if (rows.length === 0) return '';
  const lines = [
    '| Parameter | Type | Default | Description |',
    '| --- | --- | --- | --- |',
  ];
  for (const p of rows) {
    const doc = spec.docArguments[p.name];
    const type = p.annotation || (doc ? doc.type : '') || '';
    const desc = doc ? doc.description : '';
    lines.push(
      `| \`${p.name}\` | ${type ? '`' + esc(type) + '`' : ''} | ${defaultCell(p)} | ${esc(desc)} |`,
    );
  }
  return lines.join('\n');
}

/** One command rendered as an anchored H3 section. */
function commandSection(name, spec) {
  const parts = [`### cmd.${name}`, ''];
  const description = summarize(spec.sections.DESCRIPTION);
  if (description) parts.push(description, '');
  const table = paramsTable(spec);
  if (table) parts.push(table, '');
  const see = (spec.sections['SEE ALSO'] ?? '').trim();
  if (see) {
    const refs = see
      .split(/[\n,]/)
      .map((s) => s.trim())
      .filter(Boolean)
      .map((s) => '`' + s + '`')
      .join(', ');
    parts.push(`**See also:** ${refs}`, '');
  }
  return parts.join('\n');
}

function frontmatter(title, description) {
  return ['---', `title: "${title}"`, `description: "${description}"`, '---', '', GENERATED_NOTE, ''].join(
    '\n',
  );
}

function page(title, description, body) {
  return frontmatter(title, description) + '\n' + body.trimEnd() + '\n';
}

function main() {
  const argv = process.argv.slice(2);
  const schemaPath = argv[0] || join(REPO, 'tools', 'gen-api', 'api-schema.json');
  const outDir = argv[1] || join(REPO, 'docs', 'api-reference');
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));

  const names = Object.keys(schema.commands).sort();
  const safe = names.filter((n) => !UNSAFE.has(n));
  const unsafe = names.filter((n) => UNSAFE.has(n));

  mkdirSync(outDir, { recursive: true });

  // ---- index -------------------------------------------------------------
  const index = [
    'The `cmd.*` surface is the command API of the PyMOL engine, reachable from',
    'the browser through the typed client (`@tenmol/client`) over the wire',
    'protocol. These pages are generated from a live PyMOL introspection — see',
    '`tools/gen-api/` — and cover every command the bridge can dispatch.',
    '',
    '<CardGroup cols={2}>',
    `  <Card title="Commands" icon="terminal" href="/api-reference/commands">`,
    `    ${safe.length} introspectable commands with parameters and defaults.`,
    '  </Card>',
    `  <Card title="Unsafe commands" icon="triangle-exclamation" href="/api-reference/unsafe-commands">`,
    `    ${unsafe.length} commands that run arbitrary text or end the session.`,
    '  </Card>',
    `  <Card title="Settings" icon="sliders" href="/api-reference/settings">`,
    `    ${schema.domains.settings.length} setting names for \`set\`/\`get\`.`,
    '  </Card>',
    `  <Card title="Colors" icon="palette" href="/api-reference/colors">`,
    `    ${schema.domains.colors.length} named colors.`,
    '  </Card>',
    '</CardGroup>',
  ].join('\n');
  writeFileSync(
    join(outDir, 'index.mdx'),
    page('API reference', 'The generated cmd.* command surface, settings, and colors.', index),
    'utf8',
  );

  // ---- safe commands -----------------------------------------------------
  const commandsBody = [
    `<Info>${safe.length} commands, introspected from a live PyMOL. Call them through`,
    '`@tenmol/client` — e.g. `await cmd.color("red", "chainA")`.</Info>',
    '',
    ...safe.map((n) => commandSection(n, schema.commands[n])),
  ].join('\n');
  writeFileSync(
    join(outDir, 'commands.mdx'),
    page('Commands', `All ${safe.length} cmd.* commands with parameters and defaults.`, commandsBody),
    'utf8',
  );

  // ---- unsafe commands ---------------------------------------------------
  const unsafeBody = [
    '<Warning>',
    'These commands execute arbitrary text or end the session. A typed wrapper',
    'around `do` is a typed wrapper around "run anything"; treat them as a',
    'separate, guarded surface.',
    '</Warning>',
    '',
    ...unsafe.map((n) => commandSection(n, schema.commands[n])),
  ].join('\n');
  writeFileSync(
    join(outDir, 'unsafe-commands.mdx'),
    page('Unsafe commands', 'Commands that execute arbitrary text or end the session.', unsafeBody),
    'utf8',
  );

  // ---- settings ----------------------------------------------------------
  const settings = [...schema.domains.settings].sort();
  const settingsBody = [
    `<Info>${settings.length} setting names PyMOL knows, for \`cmd.set\` / \`cmd.get\`.</Info>`,
    '',
    ...settings.map((s) => `- \`${s}\``),
  ].join('\n');
  writeFileSync(
    join(outDir, 'settings.mdx'),
    page('Settings', `The ${settings.length} setting names for set/get.`, settingsBody),
    'utf8',
  );

  // ---- colors ------------------------------------------------------------
  const colors = [...schema.domains.colors].sort();
  const colorsBody = [
    `<Info>${colors.length} named colors.</Info>`,
    '',
    ...colors.map((c) => `- \`${c}\``),
  ].join('\n');
  writeFileSync(
    join(outDir, 'colors.mdx'),
    page('Colors', `The ${colors.length} named colors.`, colorsBody),
    'utf8',
  );

  console.error(
    `emit-docs: ${safe.length} commands, ${unsafe.length} unsafe, ` +
      `${settings.length} settings, ${colors.length} colors -> ${outDir}`,
  );
  return 0;
}

process.exit(main());
