/**
 * @tenmol/stores — the client state layer.
 *
 * ============================================================================
 *  THE ONE RULE FOR EVERY LATER WORK PACKAGE
 *
 *  Add `packages/stores/src/<yourStore>.ts` and DO NOT EDIT THIS FILE.
 *
 *  Consumers reach a store by its subpath — `import { ... } from
 *  '@tenmol/stores/view'` — which `package.json` (`"./*": "./src/*.ts"`) and
 *  `tsconfig.base.json` (`"@tenmol/stores/*"`) already resolve. That is why this
 *  barrel can be frozen while the package keeps growing: plan §5.2 resolves
 *  shared-file collisions structurally, and a barrel that every work package has
 *  to append to is precisely the shared file it was trying to abolish.
 *
 *  Plan §6 assigns the remaining stores:
 *    view.ts      WP-09    selection.ts WP-10    settings.ts WP-15
 *    wizard.ts    WP-16    editor.ts    WP-17    dialog.ts   WP-18
 *    movie.ts     WP-20    seqview.ts   WP-21    colors.ts   WP-22
 *    plugin.ts    WP-25    geometry.ts  WP-26
 * ============================================================================
 *
 * WHAT THIS PACKAGE IS: ~600 lines of plain TypeScript with one dependency
 * (`@tenmol/protocol`, types only), no framework and no state library. The React
 * binding is `apps/web/src/app/hooks.ts` — deliberately not here, so every rule
 * below is testable under vitest's node environment with no DOM.
 *
 * WHAT IT IS NOT: optimistic. Nothing except `ui.ts` writes a value it has not
 * read back from PyMOL. A settings write can silently no-op at the wrong level,
 * `SettingGenerateSideEffects` can invalidate geometry, and the object panel has
 * no push feed at all — so the truth is always the next poll or the next topic
 * event.
 */

/* --- the machinery ------------------------------------------------------- */

export {
  createStore,
  shallowEqual,
  type Store,
  type Listener,
  type Unsubscribe,
  type Updater,
} from './createStore';

export {
  createTopicBinding,
  invalidationsOf,
  type TopicBinding,
  type TopicBindingOptions,
  type TopicUnsubscribe,
  type InvalidationClass,
} from './bridgeBinding';

export { createPoller, type Poller, type PollerOptions, type PollerStats } from './poll';

/* --- the stores this work package owns ----------------------------------- */

export {
  createConnectionStore,
  describeConnection,
  engineState,
  CLOSE_CODE,
  type BridgeHello,
  type ConnectionPhase,
  type ConnectionState,
  type ConnectionStore,
  type EngineState,
} from './connection';

export {
  createFeedbackStore,
  classifyLine,
  overlapLength,
  type FeedbackEntry,
  type FeedbackKind,
  type FeedbackState,
  type FeedbackStore,
  type FeedbackStoreOptions,
} from './feedback';

export {
  createObjectsStore,
  buildRows,
  bitmaskFromRepIndices,
  displayName,
  rowsEqual,
  visibleRows,
  type BuildRowsInput,
  type RowSource,
  type ObjectsState,
  type ObjectsStore,
  type PanelRow,
  type VisEntry,
  type VisMap,
} from './objects';

export {
  createObjectsSource,
  panelActions,
  quoteName,
  type CallFn,
  type ObjectsSource,
  type ObjectsSourceOptions,
  type PanelAction,
} from './objectsSource';

export { createUiStore, UI_DEFAULTS, type StorageLike, type UiState, type UiStore } from './ui';
