"""Parity area 6, wave 9 — what ``cmd.save`` actually WRITES.

Four inventory rows, one theme: wave 4 proved the *dialogs* around the export
side and left the writes themselves mostly unexercised.

* row 267 ``cmd.save`` + ``savefunctions`` -- "Most of the 31 formats were not
  written."  Every entry of ``save_formats()`` is written here, from one
  deterministic scene, and the outcome of each is pinned: the bytes on disk,
  or the exact refusal.
* row 272 geometry exports -- "COLLADA (.dae) was NOT written."  It is now, and
  it is parsed as XML rather than weighed.
* row 268 ``multisave`` -- "``multisave`` itself was NOT exercised."
* row 261 session load -- "only the .pse extension was exercised".  That clause
  is STALE (wave 8's ``test_p8_a6.py::TestSessionExtensions`` already writes and
  reads ``.pze``/``.psw``/``.pzw``); what was genuinely untested is the OTHER
  half of ``load_pse``: the bzip2 branch of ``cmd.file_read``, the movie rewind,
  and the ``presentation`` half of the auto-start condition -- which turns out
  to be unreachable.

Run::

    bridge/.venv/bin/python -m pytest bridge/tests/test_p9_f2.py -q
"""

from __future__ import annotations

import os
import sys
import xml.etree.ElementTree as ET
from typing import Any, Dict, List

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tenmol_bridge.panels import files as files_panel  # noqa: E402

from conftest import WSClient  # noqa: E402

NS = "cmd.tenmol_files"
BOOTSTRAP = "import tenmol_bridge.panels.files as _tf; _tf.install()"

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
IL2 = os.path.join(ROOT, "test", "dat", "il2.pdb")
#: 257 kB, the smallest CCP4 in the tree -- ``emd_1155.ccp4`` is 3.6 MB and
#: writes a 14 MB copy, which is a lot of disk for "the ccp4 writer runs".
SMALL_MAP = os.path.join(ROOT, "testing", "data", "h2o-elf-nstart.ccp4")

MOL = "p9f2mol"
COPY = "p9f2cop"
ALN = "p9f2aln"
MAP = "p9f2map"


@pytest.fixture
def files(ws: WSClient) -> WSClient:
    ws.do(BOOTSTRAP)
    return ws


@pytest.fixture
def scene(files: WSClient):
    """One scene for the whole sweep, and every global it disturbs put back.

    ONE PYMOL PER SUITE.  ``cmd.delete all`` is the same blast radius
    ``test_geometry_exports.py`` and ``test_p8_a6.py`` already accept, but the
    camera, ``session_file`` and the representation state are process globals
    that outlive the objects, so they are snapshotted.
    """
    view = files.call("cmd.get_view")
    session_file = files.call("cmd.get", "session_file")

    files.call("cmd.delete", "all")
    files.call("cmd.load", IL2, MOL)
    files.call("cmd.create", COPY, MOL)
    files.call("cmd.align", COPY, MOL, object=ALN)
    files.call("cmd.load", SMALL_MAP, MAP)
    # Geometry exports serialise WHAT IS SHOWN, so the scene is trimmed to five
    # residues of sticks: the same object with everything shown writes a 24 MB
    # COLLADA (measured), which is 24 MB of nothing extra to assert.
    files.call("cmd.hide", "everything")
    files.call("cmd.show", "sticks", "%s and resi 1-5" % MOL)

    yield files

    files.call("cmd.delete", "all")
    files.call("cmd.set", "session_file", session_file)
    files.call("cmd.set_view", view)


# =========================================================================== #
# Row 267 — cmd.save core + the savefunctions registry
# =========================================================================== #

#: The selection argument is NOT uniform across the registry: ``get_ccp4str``
#: is bound to the ``name`` alias and ``get_alnstr`` wants the alignment object,
#: while the session writers read it as a NAMES FILTER (see
#: ``test_a_names_filter_silently_writes_an_empty_session``).
SELECTION_FOR = {
    "ccp4": MAP,
    "mrc": MAP,
    "map": MAP,
    "aln": ALN,
    "pse": "",
    "psw": "",
}

#: What each format leaves on disk, MEASURED.  ``head`` is asserted against the
#: first bytes of the file, so a writer that starts emitting something else is
#: caught; ``min_size`` only guards against a truncated write.
WRITES: Dict[str, Dict[str, Any]] = {
    "aln": {"head": b"CLUSTAL", "min_size": 200},
    "bcif": {"head": b"\x83\xaadataBlocks", "min_size": 10000},
    "ccp4": {"head": b"\x28\x00\x00\x00", "min_size": 257024},
    "cif": {"head": b"# generated by PyMOL", "min_size": 10000},
    "dae": {"head": b'<?xml version="1.0" encoding="UTF-8"?>', "min_size": 5000},
    "dat": {"head": b"  4168  untitled", "min_size": 10000},
    "fasta": {"head": b">" + MOL.encode(), "min_size": 100},
    "idtf": {"head": b'FILE_FORMAT "IDTF"', "min_size": 500},
    "mae": {"head": b"{ s_m_m2io_version ::: 2.0.0 }", "min_size": 10000},
    "map": {"head": b"\x28\x00\x00\x00", "min_size": 257024},
    "mmd": {"head": b"  4168  untitled", "min_size": 10000},
    "mmod": {"head": b"  4168  untitled", "min_size": 10000},
    "mmtf": {"head": b"\xde\x00\x1a\xaaaltLocList", "min_size": 10000},
    "mol": {"head": MOL.encode() + b"\n  PyMOL", "min_size": 10000},
    "mol2": {"head": b"# created with PyMOL", "min_size": 10000},
    "mrc": {"head": b"\x28\x00\x00\x00", "min_size": 257024},
    "out": {"head": b"  4168  untitled", "min_size": 10000},
    "pdb": {"head": b"ATOM      1  N   SER", "min_size": 10000},
    "pkl": {"head": b"ccopy_reg\n_reconstructor\nq\x00(cchempy.models", "min_size": 10000},
    "pkla": {"head": b"ccopy_reg\n_reconstructor\np0\n(cchempy.models", "min_size": 10000},
    "pov": {"head": b"camera {direction", "min_size": 1000},
    "pqr": {"head": b"ATOM      1  N   SER", "min_size": 10000},
    "pse": {"head": b"}q\x00", "min_size": 1000},
    "psw": {"head": b"}q\x00", "min_size": 1000},
    "sdf": {"head": MOL.encode() + b"\n  PyMOL", "min_size": 10000},
    "wrl": {"head": b"#VRML V2.0 utf8", "min_size": 5000},
    # MEASURED, and not a typo: the XYZ writer emits ONE molecule (2084 atoms,
    # the first object) where every other molecular writer emits both objects
    # of the selection (4168) -- see the mmod/dat/out heads above.
    "xyz": {"head": b"2084      \n" + MOL.encode(), "min_size": 10000},
}

#: The three that raise, and the one that succeeds while writing nothing.
#: ``obj``'s emptiness is a property of the SCENE (`get_mtl_obj` serialises
#: triangles only), which is why it is a separate test rather than a refusal.
REFUSES: Dict[str, str] = {
    "gltf": "could not find collada2gltf",
    "mtl": ".MTL export not implemented",
    "stl": "STL export not supported by this PyMOL build",
}

EMPTY = {"obj"}

#: ``png`` is the only entry that needs a GL context, so it is gated and
#: asserted separately.
GL_ONLY = {"png"}


def write(ws: WSClient, fmt: str, target: str) -> Dict[str, Any]:
    """``cmd.save`` one format; report what happened, never raise."""
    selection = SELECTION_FOR.get(fmt, "all")
    reply = ws.call_reply("cmd.save", target, selection, -1)
    if reply["t"] == "err":
        return {"ok": False, "error": str(reply["error"].get("message", ""))}
    out: Dict[str, Any] = {"ok": True, "result": reply["result"], "size": -1, "head": b""}
    if os.path.exists(target):
        out["size"] = os.path.getsize(target)
        with open(target, "rb") as handle:
            out["head"] = handle.read(64)
    return out


class TestSaveRegistrySweep:
    """Row 267 — every ``save_formats()`` entry, actually written."""

    def test_the_manifest_and_the_registry_agree(self, files: WSClient) -> None:
        """``save_formats()`` must cover BOTH dispatch tables in ``cmd.save``.

        ``cmd.save`` has two: ``savefunctions`` and the local ``func_type4``
        (``exporting.py:853-857``) for the chempy writers.  ``mmod`` lives only
        in the second one and was missing from the answer, even though
        ``save_check`` calls ``x.mmod`` recognised -- the two halves of the
        service disagreed about one extension.
        """
        from pymol import exporting

        formats = files.call(NS + ".save_formats")
        assert set(formats) >= set(exporting.savefunctions), "savefunctions key lost"
        assert {"mmod", "pkl", "pkla"} <= set(formats), (
            "func_type4 is a dispatch table of cmd.save too"
        )
        # ...and nothing in the list may be an extension the picker would then
        # reject on the way out.
        for fmt in formats:
            check = files.call(NS + ".save_check", "/tmp/p9f2." + fmt)
            assert check["recognised"] is True, (fmt, check)

    def test_every_format_in_the_registry_is_written_or_refused(
        self, scene: WSClient, tmp_path
    ) -> None:
        """The sweep.  One scene, 32 targets, no format left unattempted.

        The three tables above are a RECORD OF MEASUREMENT, not a
        reimplementation: each entry is checked against the bytes this run put
        on disk, so changing a writer (or losing one) reddens the test.
        """
        ws = scene
        formats = [f for f in ws.call(NS + ".save_formats") if f not in GL_ONLY]
        assert len(formats) == 31, formats

        unattempted: List[str] = []
        for fmt in formats:
            target = str(tmp_path / ("sweep." + fmt))
            outcome = write(ws, fmt, target)

            if fmt in REFUSES:
                assert outcome["ok"] is False, (fmt, outcome)
                assert REFUSES[fmt] in outcome["error"], (fmt, outcome["error"])
            elif fmt in EMPTY:
                assert outcome["ok"] is True, (fmt, outcome)
                assert outcome["size"] == 0, (fmt, outcome)
            elif fmt in WRITES:
                want = WRITES[fmt]
                assert outcome["ok"] is True, (fmt, outcome)
                assert outcome["size"] >= want["min_size"], (fmt, outcome["size"])
                assert outcome["head"].startswith(want["head"]), (fmt, outcome["head"])
            else:
                unattempted.append(fmt)

        assert unattempted == [], (
            "a format is in save_formats() with no recorded outcome: %r" % unattempted
        )
        # Every non-refusing writer really produced a distinct file.
        written = sorted(
            name for name in os.listdir(str(tmp_path)) if name.startswith("sweep.")
        )
        assert len(written) == len(WRITES) + len(EMPTY), written

    @pytest.mark.gl
    def test_png_is_the_one_entry_that_writes_the_file_itself(
        self, scene: WSClient, gl_bridge, tmp_path
    ) -> None:
        """``cmd.save``'s signature introspection has an early return.

        ``exporting.py:895-897``: if the ``savefunctions`` entry takes a
        ``filename`` parameter, ``save`` assumes the function wrote the file
        and RETURNS ITS STATUS instead of writing anything.  ``png`` is the
        only such entry, and it is observable: every other writer makes
        ``cmd.save`` return ``None``, ``png`` makes it return ``1``.
        """
        ws = scene
        target = str(tmp_path / "sweep.png")
        outcome = write(ws, "png", target)
        assert outcome["ok"] is True, outcome
        assert outcome["result"] == 1, outcome
        assert outcome["head"].startswith(b"\x89PNG\r\n\x1a\n"), outcome["head"]
        assert outcome["size"] > 1000, outcome

        other = write(ws, "pdb", str(tmp_path / "notpng.pdb"))
        assert other["result"] is None, "only the filename-taking writers return a status"

    def test_the_unavailable_manifest_is_exactly_the_measured_failures(
        self, scene: WSClient, tmp_path
    ) -> None:
        """``SAVE_UNAVAILABLE_FORMATS`` is the client's only warning, so it is
        checked against the engine rather than against itself.

        Everything the manifest lists must really fail (or write nothing), and
        nothing it omits may fail -- otherwise the picker offers a format that
        dies at ``Save``.
        """
        ws = scene
        annotated = {
            key.lstrip("."): value
            for key, value in files_panel.SAVE_UNAVAILABLE_FORMATS.items()
        }
        broken = set()
        for fmt in ws.call(NS + ".save_formats"):
            if fmt in GL_ONLY:
                continue
            outcome = write(ws, fmt, str(tmp_path / ("m." + fmt)))
            if not outcome["ok"] or outcome["size"] == 0:
                broken.add(fmt)
        # `.glb` is annotated as an alias of gltf and is not a registry key.
        assert broken == set(annotated) - {"glb"}, (broken, sorted(annotated))
        assert broken == set(REFUSES) | EMPTY

    def test_idtf_is_a_PAIR_and_save_concatenates_it(
        self, scene: WSClient, tmp_path
    ) -> None:
        """``exporting.py:900-901`` joins a returned sequence into one file.

        ``get_idtf`` returns ``(node, resource)``.  If ``save`` wrote only
        ``contents[0]`` the file would still look like a valid IDTF header --
        so the proof is arithmetic: the file is byte-for-byte both halves.
        """
        ws = scene
        target = str(tmp_path / "pair.idtf")
        assert write(ws, "idtf", target)["ok"] is True
        parts = ws.call("cmd.get_idtf")
        blobs = parts["__blobs__"] if isinstance(parts, dict) else parts
        assert isinstance(blobs, list) and len(blobs) == 2, parts
        sizes = [int(b["size"]) for b in blobs]
        assert os.path.getsize(target) == sum(sizes), (os.path.getsize(target), sizes)
        assert min(sizes) > 0, sizes

    def test_gz_and_bz2_wrap_whatever_the_writer_returned(
        self, scene: WSClient, tmp_path
    ) -> None:
        """``exporting.py:905-919``: the compression is ``save``'s, not the
        writer's, so it applies to any string-returning format.

        Both are round-tripped through ``cmd.load``, because a compressed file
        PyMOL cannot read again would pass a magic-byte check.
        """
        ws = scene
        plain = str(tmp_path / "z.pdb")
        gz = str(tmp_path / "z.pdb.gz")
        bz2 = str(tmp_path / "z.pdb.bz2")
        for target in (plain, gz, bz2):
            ws.call("cmd.save", target, MOL, -1)

        with open(gz, "rb") as handle:
            assert handle.read(2) == b"\x1f\x8b"
        with open(bz2, "rb") as handle:
            assert handle.read(3) == b"BZh"
        assert os.path.getsize(gz) < os.path.getsize(plain)
        assert os.path.getsize(bz2) < os.path.getsize(plain)

        atoms = ws.call("cmd.count_atoms", MOL)
        for target, name in ((gz, "p9f2gz"), (bz2, "p9f2bz")):
            ws.call("cmd.load", target, name)
            assert ws.call("cmd.count_atoms", name) == atoms, target
            ws.call("cmd.delete", name)

    def test_a_names_filter_silently_writes_an_empty_session(
        self, scene: WSClient, tmp_path
    ) -> None:
        """A TRAP in ``cmd.save``, measured -- and the reason the web client's
        Save Session must keep passing no selection at all.

        For ``pse``/``psw`` the second argument is not an atom selection, it is
        the ``names`` filter of ``cmd.get_session``.  ``get_psestr``
        (``exporting.py:975-979``) drops it only when it contains a bracket, and
        ``selector.process`` leaves a bare ``all`` bare -- so
        ``cmd.save(f, 'all')`` writes a session with NO OBJECTS IN IT, returns
        success, and reloads as an empty scene.
        """
        ws = scene
        default = str(tmp_path / "full.pse")
        filtered = str(tmp_path / "filtered.pse")
        ws.call("cmd.save", default)
        ws.call("cmd.save", filtered, "all", -1)
        assert os.path.getsize(filtered) * 4 < os.path.getsize(default), (
            os.path.getsize(filtered),
            os.path.getsize(default),
        )

        before = sorted(ws.call("cmd.get_names", "all"))
        ws.call("cmd.load", filtered)
        assert ws.call("cmd.get_names", "all") == [], (
            "a names-filtered .pse restores an EMPTY scene"
        )
        ws.call("cmd.load", default)
        assert sorted(ws.call("cmd.get_names", "all")) == before

        # ...and this is exactly why the client's Save Session emits no
        # selection: `cmd.save`'s own default is `(all)`, which the bracket
        # test does catch.
        from pymol import selector

        assert "(" in selector.process("(all)") and "(" not in selector.process("all")


# =========================================================================== #
# Row 272 — geometry/scene exports, and COLLADA in particular
# =========================================================================== #


class TestGeometryExports:
    def test_collada_is_real_xml_with_the_scene_in_it(
        self, scene: WSClient, tmp_path
    ) -> None:
        """Row 272's gap: ``.dae`` had never been WRITTEN.

        Weighing the file would not prove much, so it is parsed: a COLLADA root
        in the 1.4.1 namespace, with the geometry and visual-scene libraries a
        consumer actually reads, and at least one ``<float_array>`` of
        coordinates.
        """
        ws = scene
        target = str(tmp_path / "geom.dae")
        assert write(ws, "dae", target)["ok"] is True
        tree = ET.parse(target)
        root = tree.getroot()
        assert root.tag == "{http://www.collada.org/2005/11/COLLADASchema}COLLADA"
        libraries = {
            child.tag.rsplit("}", 1)[-1] for child in root
        }
        assert {"library_geometries", "library_visual_scenes", "scene"} <= libraries, (
            libraries
        )
        arrays = root.findall(
            ".//{http://www.collada.org/2005/11/COLLADASchema}float_array"
        )
        assert arrays, "a COLLADA with no coordinates is not an export"
        assert int(arrays[0].get("count", "0")) > 0

    def test_the_five_menu_formats_land_on_three_writers_and_two_walls(
        self, scene: WSClient, tmp_path
    ) -> None:
        """``pymol_qt_gui.py:793-821`` offers wrl/dae/pov/stl/gltf.

        Three write; two cannot in this build, and they fail DIFFERENTLY --
        ``stl`` is Incentive-only, ``gltf`` is a missing external binary --
        which is why ``GEOMETRY_EXPORTS`` carries a per-format reason rather
        than one "not supported" string.
        """
        ws = scene
        offered = [item["format"] for item in files_panel.GEOMETRY_EXPORTS]
        assert sorted(offered) == ["dae", "gltf", "pov", "stl", "wrl"], offered
        for fmt in offered:
            outcome = write(ws, fmt, str(tmp_path / ("menu." + fmt)))
            if fmt in REFUSES:
                assert outcome["ok"] is False, fmt
            else:
                assert outcome["ok"] is True and outcome["size"] > 1000, (fmt, outcome)

    def test_obj_writes_an_empty_file_for_a_lines_only_scene(
        self, scene: WSClient, tmp_path
    ) -> None:
        """The manifest's ``.obj`` warning, proven both ways.

        ``get_mtl_obj`` serialises TRIANGLES only, and ``cmd.save`` happily
        writes the resulting empty string -- a zero-byte file and a success
        return.  Showing a surface on the same atoms turns the same call into a
        real Wavefront OBJ, which is what makes the manifest's wording ("a
        lines-only scene writes 0 bytes") the accurate one.
        """
        ws = scene
        sticks = str(tmp_path / "sticks.obj")
        assert write(ws, "obj", sticks) == {
            "ok": True,
            "result": None,
            "size": 0,
            "head": b"",
        }

        ws.call("cmd.show", "surface", "%s and resi 1-5" % MOL)
        ws.call("cmd.rebuild")
        solid = str(tmp_path / "surface.obj")
        outcome = write(ws, "obj", solid)
        ws.call("cmd.hide", "surface")
        assert outcome["ok"] is True and outcome["size"] > 1000, outcome
        with open(solid, "rb") as handle:
            body = handle.read()
        assert b"\nv " in body and b"\nf " in body, body[:200]


# =========================================================================== #
# Row 268 — multisave / multifilesave / multifilenamegen
# =========================================================================== #


class TestMultisave:
    """Row 268's gap: ``multisave`` itself was never run."""

    def test_a_multi_entry_pdb_reloads_as_SEPARATE_objects(
        self, scene: WSClient, tmp_path
    ) -> None:
        """The whole point of ``multisave`` over ``save``, measured on both.

        ``exporting.py:604-622``: every object gets its own HEADER and its own
        END, so PyMOL reads the file back as N objects.  The flat ``cmd.save``
        of the same selection has no HEADER at all and comes back as ONE.
        """
        ws = scene
        multi = str(tmp_path / "multi.pdb")
        flat = str(tmp_path / "flat.pdb")
        assert ws.call_reply("cmd.multisave", multi, "all", -1)["t"] == "ok"
        ws.call("cmd.save", flat, "all", -1)

        with open(multi) as handle:
            multi_text = handle.read()
        with open(flat) as handle:
            flat_text = handle.read()
        assert multi_text.count("HEADER") == 2, multi_text[:200]
        assert multi_text.count("\nEND\n") == 2
        assert multi_text.startswith("HEADER    %s\n" % MOL)
        assert "HEADER    %s\n" % COPY in multi_text
        assert flat_text.count("HEADER") == 0
        assert flat_text.startswith("ATOM ")

        ws.call("cmd.delete", "all")
        ws.call("cmd.load", multi, "p9f2multi")
        assert sorted(ws.call("cmd.get_names", "all")) == [COPY, MOL], (
            "multisave's HEADER records are what split it back into objects"
        )
        ws.call("cmd.delete", "all")
        ws.call("cmd.load", flat, "p9f2flat")
        assert ws.call("cmd.get_names", "all") == ["p9f2flat"]

    def test_cif_is_the_other_supported_format_and_writes_two_datablocks(
        self, scene: WSClient, tmp_path
    ) -> None:
        ws = scene
        target = str(tmp_path / "multi.cif")
        assert ws.call_reply("cmd.multisave", target, "all", -1)["t"] == "ok"
        with open(target) as handle:
            text = handle.read()
        assert "data_%s\n" % MOL in text and "data_%s\n" % COPY in text
        assert text.count("_entry.id") == 2, text[:200]

    def test_append_adds_to_the_file_instead_of_truncating_it(
        self, scene: WSClient, tmp_path
    ) -> None:
        """``append=1`` opens ``'a'`` (``exporting.py:653``).

        Asserted on the ENTRY COUNT, not the size: a truncating writer that
        happened to write the same bytes twice would pass a size check on the
        second call.
        """
        ws = scene
        target = str(tmp_path / "append.pdb")
        ws.call("cmd.multisave", target, MOL, -1)
        first = os.path.getsize(target)
        ws.call("cmd.multisave", target, COPY, -1, 1)
        with open(target) as handle:
            text = handle.read()
        assert os.path.getsize(target) > first
        assert text.count("HEADER") == 2, text[:120]
        assert "HEADER    %s\n" % MOL in text and "HEADER    %s\n" % COPY in text

        # and without append the second write replaces the first
        ws.call("cmd.multisave", target, COPY, -1)
        with open(target) as handle:
            text = handle.read()
        assert text.count("HEADER") == 1
        assert "HEADER    %s\n" % MOL not in text

    @pytest.mark.parametrize(
        "name,message",
        [
            ("no.pdb.gz", "gz not supported with multisave"),
            ("no.pdb.bz2", "bz2 not supported with multisave"),
            ("no.pmo", "pmo format not supported anymore"),
            ("no.sdf", "sdf format not supported with multisave"),
            ("no.pse", "pse format not supported with multisave"),
        ],
    )
    def test_the_four_refusals_are_distinct_messages(
        self, scene: WSClient, tmp_path, name: str, message: str
    ) -> None:
        """``exporting.py:634-645``, in order: compression, then ``pmo``, then
        anything that is not pdb/cif.  Each refusal must reach the client as
        its own sentence -- the Export Molecule dialog's multisave checkbox is
        the only thing standing between a user and these.
        """
        ws = scene
        target = str(tmp_path / name)
        reply = ws.call_reply("cmd.multisave", target, "all", -1)
        assert reply["t"] == "err", (name, reply)
        assert message in str(reply["error"]["message"]), (name, reply["error"])
        assert not os.path.exists(target), "a refused multisave must write nothing"

    def test_multifilesave_and_the_bridge_generator_wrapper_agree(
        self, scene: WSClient, tmp_path
    ) -> None:
        """The preview the dialog shows must be the files it then writes.

        ``multifilenamegen`` is consumed on the engine side (it is a generator;
        the codec refuses ``builtins.generator``), and ``multifilesave`` loops
        the SAME generator through ``cmd.save`` -- so the preview list and the
        directory listing have to match exactly.
        """
        ws = scene
        pattern = str(tmp_path / "{name}.pdb")
        preview = ws.call(NS + ".multifilenamegen", pattern, "all", -1)
        assert preview["ok"] is True, preview
        assert [os.path.basename(item["filename"]) for item in preview["items"]] == [
            MOL + ".pdb",
            COPY + ".pdb",
        ]
        ws.call("cmd.multifilesave", pattern, "all", -1)
        for item in preview["items"]:
            assert os.path.getsize(item["filename"]) > 1000, item

    def test_a_pattern_with_no_placeholder_is_an_error_not_a_traceback(
        self, scene: WSClient, tmp_path
    ) -> None:
        preview = scene.call(NS + ".multifilenamegen", str(tmp_path / "flat.pdb"), "all", -1)
        assert preview["ok"] is False
        assert "need one or more of {name}, {num}, {state}, {title}" in preview["error"]
        assert preview["items"] == []


# =========================================================================== #
# Row 261 — session load (.pse/.psw/.pze/.pzw)
# =========================================================================== #


@pytest.fixture
def session_globals(files: WSClient):
    """A session load steals EVERY global; this puts the disturbed ones back.

    Scenes, the movie, the frame, the camera, ``session_file`` and the two
    presentation settings are all process state that ``set_session(steal=1)``
    replaces wholesale (``importing.py:836``).
    """
    view = files.call("cmd.get_view")
    session_file = files.call("cmd.get", "session_file")
    presentation = files.call("cmd.get", "presentation")
    auto_start = files.call("cmd.get", "presentation_auto_start")
    scenes = list(files.call("cmd.get_scene_list") or [])

    yield files

    for name in list(files.call("cmd.get_scene_list") or []):
        if name not in scenes:
            files.call("cmd.scene", name, "delete")
    files.call("cmd.delete", "all")
    files.call("cmd.mset")
    files.call("cmd.set", "presentation_auto_start", auto_start)
    files.call("cmd.set", "presentation", presentation)
    files.call("cmd.set", "session_file", session_file)
    files.call("cmd.set_view", view)


def make_show_session(ws: WSClient, target: str) -> None:
    """A session with a ten-frame movie, one scene, and the camera on frame 7."""
    ws.call("cmd.delete", "all")
    for name in list(ws.call("cmd.get_scene_list") or []):
        ws.call("cmd.scene", name, "delete")
    ws.call("cmd.fragment", "trp", "p9f2show")
    ws.call("cmd.mset", "1 x10")
    ws.call("cmd.reset")
    ws.call("cmd.scene", "P9F2SCENE", "store")
    ws.call("cmd.frame", 7)
    ws.call("cmd.save", target)


class TestSessionLoad:
    """Row 261 -- the halves of ``load_pse`` wave 4 and wave 8 left alone."""

    def test_a_bzip2_session_is_read_by_MAGIC_not_by_extension(
        self, session_globals: WSClient, tmp_path
    ) -> None:
        """``cmd.file_read``'s third branch (``internal.py:305-307``).

        ``.pze``/``.pzw`` are gzip and were covered in wave 8; bzip2 has no
        session extension at all, so the only way in is ``x.pse.bz2``, and the
        only reason it works is that ``file_read`` sniffs ``BZh...1AY&SY``
        rather than trusting the name.  Proven by RENAMING the compressed file
        to a bare ``.pse``: it still loads.
        """
        ws = session_globals
        ws.call("cmd.delete", "all")
        ws.call("cmd.fragment", "trp", "p9f2bz")
        atoms = ws.call("cmd.count_atoms", "p9f2bz")

        packed = str(tmp_path / "s.pse.bz2")
        plain = str(tmp_path / "s.pse")
        ws.call("cmd.save", packed)
        ws.call("cmd.save", plain)
        with open(packed, "rb") as handle:
            magic = handle.read(10)
        assert magic[:3] == b"BZh" and magic[4:10] == b"1AY&SY", magic
        assert os.path.getsize(packed) < os.path.getsize(plain)

        ws.call("cmd.delete", "all")
        ws.call("cmd.load", packed)
        assert ws.call("cmd.get_names", "all") == ["p9f2bz"]
        assert ws.call("cmd.count_atoms", "p9f2bz") == atoms

        # The name is irrelevant; the magic is not.
        lying = str(tmp_path / "lying.pse")
        with open(packed, "rb") as src, open(lying, "wb") as dst:
            dst.write(src.read())
        ws.call("cmd.delete", "all")
        ws.call("cmd.load", lying)
        assert ws.call("cmd.get_names", "all") == ["p9f2bz"]

    def test_a_psw_rewinds_the_movie_and_recalls_the_first_scene(
        self, session_globals: WSClient, tmp_path
    ) -> None:
        """``importing.py:846-852`` -- the branch, with a movie in it.

        Wave 8 could only reach the raising form of this (a session with NO
        scenes).  Here the session carries a ten-frame movie parked on frame 7
        and one scene: after the load the frame is 1, which is a change
        ``set_session`` alone does not make -- the same bytes named ``.pse``
        come back on frame 7.
        """
        ws = session_globals
        psw = str(tmp_path / "show.psw")
        make_show_session(ws, psw)
        pse = str(tmp_path / "show.pse")
        ws.call("cmd.frame", 7)
        ws.call("cmd.save", pse)
        assert ws.call("cmd.get_frame") == 7
        assert ws.call("cmd.get_movie_length") == 10

        ws.call("cmd.delete", "all")
        ws.call("cmd.mset")
        assert ws.call_reply("cmd.load", pse)["t"] == "ok"
        assert ws.call("cmd.get_movie_length") == 10
        assert ws.call("cmd.get_frame") == 7, "a .pse restores the saved frame"

        ws.call("cmd.delete", "all")
        ws.call("cmd.mset")
        assert ws.call_reply("cmd.load", psw)["t"] == "ok"
        assert ws.call("cmd.get_frame") == 1, "load_pse rewinds a .psw"
        assert ws.call("cmd.get", "scene_current_name") == "P9F2SCENE"

    def test_presentation_auto_start_travels_IN_the_session_and_gates_it(
        self, session_globals: WSClient, tmp_path
    ) -> None:
        """The gate is read AFTER ``set_session`` -- so it is the file's value.

        ``presentation_auto_start`` is not session-blacklisted
        (``Setting.cpp:626-684``), so a ``.psw`` written while it is off
        carries "off" and suppresses its own auto-start: the frame stays where
        the session parked it.  The live value before the load is irrelevant,
        which is the opposite of what a client that "sets it first" would
        assume.
        """
        ws = session_globals
        ws.call("cmd.set", "presentation_auto_start", 0)
        quiet = str(tmp_path / "quiet.psw")
        make_show_session(ws, quiet)

        ws.call("cmd.delete", "all")
        ws.call("cmd.mset")
        ws.call("cmd.set", "presentation_auto_start", 1)
        assert ws.call_reply("cmd.load", quiet)["t"] == "ok"
        assert ws.call("cmd.get", "presentation_auto_start") == "off", (
            "the session's value replaced the live one"
        )
        assert ws.call("cmd.get_frame") == 7, (
            "auto_start=off in the file must suppress the rewind"
        )

    def test_the_presentation_half_of_the_condition_is_DEAD_on_a_session_load(
        self, session_globals: WSClient, tmp_path
    ) -> None:
        """A measured negative that the inventory row's wording hides.

        ``load_pse`` starts the presentation for ``format == 'psw'`` OR
        ``presentation`` (``importing.py:843-845``) -- but it reads
        ``presentation`` only after ``set_session(steal=1)`` has replaced the
        whole settings table, and ``cSetting_presentation`` is on
        ``is_session_blacklisted``'s list (``layer1/Setting.cpp:626-684``), so
        it can never come back on.  Set it, save, reload: it is off, and a
        ``.pse`` never auto-starts however it was written.
        """
        ws = session_globals
        ws.call("cmd.set", "presentation_auto_start", 1)
        ws.call("cmd.set", "presentation", 1)
        target = str(tmp_path / "pres.pse")
        make_show_session(ws, target)
        assert ws.call("cmd.get", "presentation") == "on", "set before the save"

        ws.call("cmd.delete", "all")
        ws.call("cmd.mset")
        assert ws.call_reply("cmd.load", target)["t"] == "ok"
        assert ws.call("cmd.get", "presentation") == "off", (
            "presentation is blacklisted from the PSE"
        )
        assert ws.call("cmd.get_frame") == 7, "so the .pse did not auto-start"

    def test_session_file_is_rewritten_with_unix_separators(
        self, session_globals: WSClient, tmp_path
    ) -> None:
        """``importing.py:839-841`` / ``exporting.py:846-848``, and it BITES.

        Both halves do ``filename.replace('\\\\', '/')`` unconditionally.  On
        POSIX a backslash is an ordinary filename character, so saving to
        ``a\\b.pse`` writes ``a\\b.pse`` but records ``a/b.pse`` -- a path that
        does not exist.  Save Session (no dialog) would then write to a
        directory that is not there, which is why the client shows
        ``session_file`` rather than assuming it.
        """
        ws = session_globals
        ws.call("cmd.delete", "all")
        ws.call("cmd.fragment", "trp", "p9f2sep")
        weird = str(tmp_path / "a\\b.pse")
        ws.call("cmd.save", weird)
        assert os.path.exists(weird), "the file itself keeps the backslash"
        recorded = ws.call("cmd.get", "session_file")
        assert recorded == weird.replace("\\", "/") != weird
        assert not os.path.exists(recorded)

        ws.call("cmd.set", "session_file", "P9F2-SENTINEL")
        ws.call("cmd.delete", "all")
        ws.call("cmd.load", weird)
        assert ws.call("cmd.get", "session_file") == recorded, (
            "load_pse does the same substitution"
        )
        assert ws.call("cmd.get_names", "all") == ["p9f2sep"]
        # ...and the bridge's own answer carries the same broken path, which is
        # what the title bar shows.
        info = ws.call(NS + ".session_file")
        assert info["hasPath"] is True and info["path"] == recorded
